//
// Created by Ashish Gaikwad on 19/10/21.
//

import Foundation
import SwiftUI

/**
 Button element extent is used to provide all base properties to ButtonRenderer. But it uses TextElement as its parent

 - Author: Ashish Gaikwad
 - Since: 1.3.0
 */
class TextElement: BaseTextElement, Identifiable {
    // MARK: Lifecycle


    // MARK: Public

    /**
     Process parts and generate only one ``SwiftUI.Text`` by managing all their property

     - Returns: ``SwiftUI.Text`` generated by processing all parts
     */
    public func getSinglePart() -> Text {
        var text = Text("")

        for index in 0..<prs!.count {
            let part = prs![index]
            var partText = part.getPartText()
            let textColour: Color = part.getPartColour() ?? getColour() ?? Color(hex: "#000000")
            let font = getFont(for: part)

            if prs!.count - 1 == index {
                partText = Character(extendedGraphemeClusterLiteral: Array(partText)[partText.count - 1]).isNewline ?
                        String(partText.dropLast()) : partText
            }

            text = text + Text(partText)
                    .foregroundColor(textColour)
                    .font(font)
                    .bold(part.isBold())
                    .italic(part.isItalic())
                    .underline(part.addUnderLine())
                    .strikethrough(part.addStrikeThrough())
        }

        return text
    }

    // MARK: Internal

    var prs: [PartElement]?
}
